# Generated by Django 3.2.4 on 2021-06-28 22:16
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0004_spec_gear'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spec',
            name='gear',
        ),
        migrations.AddField(
            model_name='gear',
            name='spec',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
    ]
