# Generated by Django 3.2.4 on 2021-06-28 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_auto_20210628_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gear',
            name='spec',
            field=models.CharField(max_length=50),
        ),
    ]
