# Generated by Django 3.2.4 on 2021-06-30 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_alter_gear_spec'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gear',
            name='spec',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.spec'),
        ),
    ]
