# Generated by Django 3.2.4 on 2021-06-30 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_alter_gear_spec'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gear',
            name='spec',
        ),
        migrations.AddField(
            model_name='spec',
            name='gear',
            field=models.ManyToManyField(to='main_app.Gear'),
        ),
    ]
