# Generated by Django 3.2.4 on 2021-07-01 16:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0011_spec_character'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spec',
            name='gear',
        ),
        migrations.RemoveField(
            model_name='spec',
            name='user',
        ),
        migrations.AddField(
            model_name='gear',
            name='spec',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_app.spec'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gear',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
    ]
