# Generated by Django 3.2.4 on 2021-07-02 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_auto_20210701_1220'),
    ]

    operations = [
        migrations.AddField(
            model_name='gear',
            name='enchant',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gear',
            name='slot',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
